//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_Kino
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pr14_CinemaEntities : DbContext
    {
        public Pr14_CinemaEntities()
            : base("name=Pr14_CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Film_Genre> Film_Genre { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Room_Rating> Room_Rating { get; set; }
        public virtual DbSet<Seat> Seat { get; set; }
        public virtual DbSet<Segregation> Segregation { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<Session_Seat> Session_Seat { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
