//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_Kino
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session_Seat
    {
        public int ID { get; set; }
        public int ID_Session { get; set; }
        public int ID_Seat { get; set; }
        public bool Taken { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual Session Session { get; set; }
    }
}
