//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR8._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Order
    {
        public int ID { get; set; }
        public int ID_Order { get; set; }
        public int ID_User_Product { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User_Product User_Product { get; set; }
    }
}
