//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practic7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_Part
    {
        public int ID { get; set; }
        public int ID_Warehouse { get; set; }
        public int ID_Part { get; set; }
        public int Count { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual Warehouse Warehouse { get; set; }

    }
}
